---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-monkey-config-map
  namespace: kubemonkey
data:
  config.toml: |
    [kubemonkey]
    run_hour = 1
    start_hour = 2
    end_hour = 23
    time_zone = "Australia/Melbourne"
    graceperiod_sec= 10
    [debug]
    enabled= true
    schedule_immediate_kill= true
