# contains the target host names for the dns error
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-dns
spec:
  appinfo:
    appns: "litmus"
    applabel: 'app=nginx'
    appkind: deployment
  chaosServiceAccount: dns-error-sa
  monitoring: false
  jobCleanUpPolicy: delete
  experiments:
  - name: pod-dns-error
    spec:
      components:
        env:
        ## comma separated list of host names
        ## if not provided, all hostnames/domains will be targeted
        - name: TARGET_HOSTNAMES
          value: '["litmuschaos", "google.com"]'
        - name: TOTAL_CHAOS_DURATION
          value: "36600"
