apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: chaosmesh
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      "app": "nginx"
  delay:
    latency: "90ms"
    correlation: "25"
    jitter: "90ms"
  duration: "40s"
